In [31]:
import random
import numpy as np

#Generating chromosomes
def generate_population(chromosone_numbers):
    chromosome_lst=[]
    for i in range(100): #need to upadte the range around 100
        chromosome=np.random.randint(0,2,size=chromosone_numbers)
        chromosome_lst.append(chromosome)
    return chromosome_lst

#Calculating fitness for each chromosome
def fitness_calculation(chromosome_lst):
    fitness_score=[]
    for i in range(len(chromosome_lst)):
        score=0
        #Calculating fitness for each particular chromosome
        for idx, gene in enumerate(chromosome_lst[i]):
            if gene!=0:
                score+=transactions[idx]
        fitness_score.append(abs(score))
    return fitness_score

#Finding the least fit chromosome
def selection(fitness_scores):
    #print(fitness.index(min(fitness_scores)))
    return fitness.index(min(fitness_scores))

#Crossing over between 2 chromosome
def crossover(chr1,chr2):
    point=random.randint(1,len(chr1)-2)
    child_list=[]# to store the chromose of 2 offsprings
    child_list.append(chr1[:point+1]+chr2[point+1:]) #storing the chromosme of child 1
    child_list.append(chr2[:point+1]+chr1[point+1:]) #storing the chromosme of child 2
    return child_list

#Picking a random child and mutating their gene in the chromosome
def mutation(off1,off2):
    lst=[off1,off2]
    #choosing a random child's chromose to  mutate
    choice=random.choice(lst)
    #choosing a random point to mutate
    point=random.randint(0,len(off1)-1)
    if choice==off1:
        if off1[point]==0:
            off1[point]=1
        else:
            off1[point]=0
    elif choice==off2:
        if off2[point]==0:
            off2[point]=1
        else:
            off2[point]=0
    return off1,off2



target_balance=0
transactions=[]
output_sequence=np.array([]) #output list for the output
number_of_transaction=int(input("Enter the number of today'sTransactions: "))
for i in range(number_of_transaction):
    transaction_type,amount=input("Enter the transaction: ").split()
    if transaction_type=='l':
        amount=-int(amount)
    else:
        amount=int(amount)
    transactions.append(amount)

print(f'Transactions: {transactions}')

for i in range(150): #need to upadte the range around 150
    #generating population
    population=generate_population(number_of_transaction)
    print(f"Populations: {population}")

    #finding the fitnesss of each chromose in the population
    fitness=fitness_calculation(population)
    print(f'fitness Score: {fitness}')

    #Finding the least_fit chromosome so that i can later pop it from the population
    select_least_fit=selection(fitness)

    #poping the least fit chromosome from the population
    population.pop(select_least_fit)
    print(f'updated population: {population}')

    result_achieved=False

    for j in range(len(population)):
        #randomly choosing two chromose for crossing over
        chr1=random.choice(population)
        chr2=random.choice(population)
        offspr=crossover(chr1,chr2)
        offspr1,offspr2=offspr[0],offspr[1]

        mutated=mutation(offspr1,offspr2)

        #Checking if anyof the mutated chromosome help us achieve the target balance
        total_balance=0
        for x,y in enumerate(offspr1):
            if x==1:
                total_balance+=transactions[x]
        if total_balance==target_balance:
            output_sequence=np.array(offspr1)
            result_achieved=True
            break
        else:
            total_balance=0
            for x,y in enumerate(offspr2):
                if x==1:
                    total_balance+=transactions[x]
            if total_balance==target_balance:
                output_sequence=np.array(offspr2)
                result_achieved=True
                break
    
    #if result achieved terminate the code
    if result_achieved==True:
        break

if output_sequence.size!=0:
    print(f'/noutput sequence: {output_sequence}')
else:
    print(-1)


Transactions: [-120, -289, 475, -195, 6482, -160, 935]
Populations: [array([0, 0, 1, 1, 1, 0, 1]), array([1, 0, 0, 0, 1, 1, 1]), array([1, 0, 0, 1, 1, 1, 0]), array([0, 0, 0, 0, 0, 0, 1]), array([1, 1, 1, 1, 0, 0, 1]), array([0, 0, 1, 0, 1, 0, 0]), array([1, 1, 1, 1, 1, 1, 0]), array([1, 1, 0, 1, 0, 0, 1]), array([1, 1, 1, 1, 0, 1, 1]), array([0, 1, 1, 1, 0, 1, 0]), array([0, 1, 1, 1, 1, 1, 1]), array([1, 0, 0, 1, 0, 0, 0]), array([0, 0, 0, 1, 0, 1, 1]), array([1, 0, 0, 1, 1, 1, 0]), array([0, 0, 1, 0, 0, 0, 1]), array([1, 0, 0, 1, 1, 1, 1]), array([0, 0, 1, 0, 0, 1, 1]), array([1, 1, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 1, 1]), array([1, 1, 0, 1, 0, 1, 0]), array([0, 1, 1, 1, 0, 0, 1]), array([0, 0, 1, 0, 0, 0, 1]), array([1, 0, 1, 0, 1, 0, 1]), array([0, 1, 0, 0, 0, 0, 1]), array([1, 1, 1, 0, 0, 1, 1]), array([1, 1, 0, 0, 0, 1, 1]), array([1, 1, 1, 1, 1, 1, 1]), array([1, 0, 0, 1, 1, 1, 1]), array([1, 1, 1, 0, 0, 0, 1]), array([1, 1, 0, 0, 1, 1, 1]), array([0, 0, 0, 0, 1, 1, 0]), a

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [84]:
#Wasef trial 2
import random
import numpy as np

#Generating chromosomes
def generate_population(chromosone_numbers):
    chromosome_lst=[]
    for i in range(20): #need to upadte the range around 100
        chromosome=np.random.randint(0,2,size=chromosone_numbers)
        chromosome_lst.append(chromosome)
    return chromosome_lst

#Calculating fitness for each chromosome
def fitness_calculation(chromosome_lst):
    fitness_score=[]
    for i in range(len(chromosome_lst)):
        score=0
        #Calculating fitness for each particular chromosome
        for idx, gene in enumerate(chromosome_lst[i]):
            if gene!=0:
                score+=transactions[idx]
        fitness_score.append(abs(score))
    return fitness_score

#Finding the least fit chromosome
def selection(fitness_scores):
    #print(fitness.index(min(fitness_scores)))
    return fitness.index(min(fitness_scores))

#Crossing over between 2 chromosome
def crossover(chr1,chr2):
    chr1,chr2=list(chr1),list(chr2)
    print(f'char1: {chr1}\nchar2: {chr2}')
    point=random.randint(1,len(chr1)-2)
    print(f'point: {point}')
    chr1_fh,chr1_lh=chr1[:point+1],chr1[point+1:]
    chr2_fh,chr2_lh=chr2[:point+1],chr2[point+1:]
    child1=(chr1_fh+chr2_lh)
    child2=(chr2_fh+chr1_lh)
    print(f'child1: {child1}\nchild2: {child2}')
    child_lst=[]
    child_lst.append((child1))
    child_lst.append([child2])
    print(f'list :{child_lst}')
    return child_lst
    


    

#Picking a random child and mutating their gene in the chromosome
def mutation(off1,off2):
    lst=[off1,off2]
    #choosing a random child's chromose to  mutate
    choice=random.choice(lst)
    #choosing a random point to mutate
    point=random.randint(0,len(off1)-1)
    print('mutaion point', point)
    if (choice==off1).all():
        if off1[point]==0:
            off1[point]=1
        else:
            off1[point]=0
        #print('mutated off 1',off1)
    else:
        if (off2[point]==0).all():
            off2[point]=1
        else:
            off2[point]=0
        #print('mutated off 2',off2)
    print(f'off1: {off1}\n off2: {off2}')
    return off1,off2



target_balance=0
transactions=[]
output_sequence=np.array([]) #output list for the output
number_of_transaction=int(input("Enter the number of today'sTransactions: "))
for i in range(number_of_transaction):
    transaction_type,amount=input("Enter the transaction: ").split()
    if transaction_type=='l':
        amount=-int(amount)
    else:
        amount=int(amount)
    transactions.append(amount)

print(f'Transactions: {transactions}')

for i in range(150): #need to upadte the range around 150
    #generating population
    population=generate_population(number_of_transaction)
    print(f"Populations: {population}")

    #finding the fitnesss of each chromose in the population
    fitness=fitness_calculation(population)
    print(f'fitness Score: {fitness}')

    #Finding the least_fit chromosome so that i can later pop it from the population
    select_least_fit=selection(fitness)

    #poping the least fit chromosome from the population
    population.pop(select_least_fit)
    print(f'updated population: {population}')

    result_achieved=False

    for j in range(len(population)):
        #randomly choosing two chromose for crossing over
        chr1=random.choice(population)
        chr2=random.choice(population)
        offspr=crossover(chr1,chr2)
        offspr1,offspr2=offspr[0],offspr[1]

        mutated=mutation(offspr1,offspr2)

        #Checking if anyof the mutated chromosome help us achieve the target balance
        total_balance=0
        for x,y in enumerate(offspr1):
            if x==1:
                total_balance+=transactions[x]
        if total_balance==target_balance:
            if offspr1!=([0] * len(offspr1)):
                output_sequence=np.array(offspr1)
                result_achieved=True
                break
        
        total_balance=0
        for x,y in enumerate(offspr2):
            if x==1:
                total_balance+=transactions[x]
        if total_balance==target_balance:
            if offspr2!=([0] * len(offspr2)):
                output_sequence=np.array(offspr2)
                result_achieved=True
                break
    
    #if result achieved terminate the code
    if result_achieved==True:
        break

if output_sequence.size==0:
    print(-1)
    
else:
    print(f'/noutput sequence: {output_sequence}')



Transactions: [-120, -289, 475, -195, 6482, -160, 935]
Populations: [array([1, 1, 1, 0, 0, 1, 0]), array([0, 1, 1, 1, 1, 1, 0]), array([1, 0, 0, 1, 1, 1, 0]), array([0, 0, 0, 1, 1, 1, 0]), array([1, 1, 1, 1, 1, 1, 0]), array([1, 1, 0, 0, 1, 1, 1]), array([0, 1, 0, 0, 0, 0, 1]), array([0, 0, 0, 1, 0, 1, 1]), array([1, 1, 0, 0, 1, 1, 1]), array([1, 0, 0, 1, 0, 1, 0]), array([1, 1, 0, 1, 1, 0, 1]), array([1, 1, 0, 0, 1, 0, 0]), array([1, 0, 0, 1, 0, 0, 1]), array([1, 0, 0, 0, 1, 1, 0]), array([0, 1, 1, 0, 1, 1, 0]), array([1, 1, 0, 0, 0, 0, 0]), array([0, 1, 0, 0, 0, 1, 0]), array([0, 1, 0, 1, 1, 1, 0]), array([0, 1, 0, 0, 0, 1, 1]), array([1, 1, 1, 1, 0, 0, 0])]
fitness Score: [94, 6313, 6007, 6127, 6193, 6848, 646, 580, 6848, 475, 6813, 6073, 620, 6202, 6508, 409, 449, 5838, 486, 129]
updated population: [array([0, 1, 1, 1, 1, 1, 0]), array([1, 0, 0, 1, 1, 1, 0]), array([0, 0, 0, 1, 1, 1, 0]), array([1, 1, 1, 1, 1, 1, 0]), array([1, 1, 0, 0, 1, 1, 1]), array([0, 1, 0, 0, 0, 0, 1]), arra

AttributeError: 'bool' object has no attribute 'all'

In [2]:
#Wasef trial 2
import random
import numpy as np

#Generating chromosomes
def generate_population(chromosone_numbers):
    chromosome_lst=[]
    for i in range(20): #need to upadte the range around 100
        chromosome=np.random.randint(0,2,size=chromosone_numbers)
        chromosome_lst.append(chromosome)
    return chromosome_lst

#Calculating fitness for each chromosome
def fitness_calculation(chromosome_lst):
    fitness_score=[]
    for i in range(len(chromosome_lst)):
        score=0
        #Calculating fitness for each particular chromosome
        for idx, gene in enumerate(chromosome_lst[i]):
            if gene!=0:
                score+=transactions[idx]
        fitness_score.append(abs(score))
    print(fitness_score)
    return fitness_score

#Finding the least fit chromosome
def selection(fitness_scores):
    #print(fitness.index(min(fitness_scores)))
    return fitness.index(min(fitness_scores))

#Crossing over between 2 chromosome
def crossover(chr1,chr2):
    chr1,chr2=list(chr1),list(chr2)

    point=random.randint(1,len(chr1)-2)

    chr1_fh,chr1_lh=chr1[:point+1],chr1[point+1:]
    chr2_fh,chr2_lh=chr2[:point+1],chr2[point+1:]
    child1=(chr1_fh+chr2_lh)
    child2=(chr2_fh+chr1_lh)

    child_lst=[]
    child_lst.append(child1)
    child_lst.append(child2)

    return child_lst
    


    

#Picking a random child and mutating their gene in the chromosome
def mutation(off1,off2):
    print(f"offspring1: {off1}\n offrping 2: {off2}")
    #choosing a random point to mutate
    point=random.randint(0,len(off1)-1)
    print('mutaion point', point)

    if off1[point]==0:
        off1[point]=1
    else:
        off1[point]=0
        #print('mutated off 1',off1)

    if (off2[point]==0):
        off2[point]=1
    else:
        off2[point]=0
        #print('mutated off 2',off2)

    return off1,off2



target_balance=0
transactions=[]
output_sequence=np.array([]) #output list for the output
number_of_transaction=int(input("Enter the number of today'sTransactions: "))
for i in range(number_of_transaction):
    transaction_type,amount=input("Enter the transaction: ").split()
    if transaction_type=='l':
        amount=-int(amount)
    else:
        amount=int(amount)
    transactions.append(amount)



for i in range(150): #need to upadte the range around 150
    #generating population
    population=generate_population(number_of_transaction)
    

    #finding the fitnesss of each chromose in the population
    fitness=fitness_calculation(population)
    

    #Finding the least_fit chromosome so that i can later pop it from the population
    select_least_fit=selection(fitness)

    #poping the least fit chromosome from the population
    population.pop(select_least_fit)
    #print(f'updated population: {population}')

    result_achieved=False

    for j in range(len(population)):
        #randomly choosing two chromose for crossing over
        chr1=random.choice(population)
        chr2=random.choice(population)
        offspr=crossover(chr1,chr2)
        offspr1,offspr2=offspr[0],offspr[1]

        mutated=mutation(offspr1,offspr2)

        #Checking if anyof the mutated chromosome help us achieve the target balance
        total_balance=0
        for x,y in enumerate(offspr1):
            if x==1:
                total_balance+=transactions[x]
        if total_balance==target_balance:
            if offspr1!=([0] * len(offspr1)):
                output_sequence=np.array(offspr1)
                result_achieved=True
                break
        
        total_balance=0
        for x,y in enumerate(offspr2):
            if x==1:
                total_balance+=transactions[x]
        if total_balance==target_balance:
            if offspr2!=([0] * len(offspr2)):
                output_sequence=np.array(offspr2)
                result_achieved=True
                break
    
    #if result achieved terminate the code
    if result_achieved==True:
        break

if output_sequence.size==0:
    print(-1)
    
else:
    print(f'/noutput sequence: {output_sequence}')



[1215, 526, 315, 160, 0, 120, 129, 7417, 6473, 195, 315, 7483, 7603, 475, 289, 409, 764, 7612, 451, 7417]
offspring1: [0, 0, 1, 0, 1, 1, 1]
 offrping 2: [1, 0, 0, 0, 1, 0, 1]
mutaion point 2
offspring1: [0, 0, 1, 0, 0, 0, 0]
 offrping 2: [1, 0, 1, 1, 0, 1, 0]
mutaion point 3
offspring1: [1, 0, 0, 1, 0, 0, 0]
 offrping 2: [0, 0, 1, 0, 1, 1, 1]
mutaion point 3
offspring1: [0, 0, 0, 1, 0, 0, 0]
 offrping 2: [1, 0, 0, 0, 0, 0, 0]
mutaion point 6
offspring1: [1, 1, 1, 0, 1, 0, 1]
 offrping 2: [1, 1, 0, 1, 0, 1, 0]
mutaion point 2
offspring1: [0, 0, 0, 0, 1, 0, 1]
 offrping 2: [1, 0, 1, 0, 1, 1, 1]
mutaion point 2
offspring1: [1, 1, 1, 1, 0, 0, 1]
 offrping 2: [0, 0, 0, 0, 1, 0, 0]
mutaion point 3
offspring1: [1, 1, 0, 1, 0, 1, 1]
 offrping 2: [0, 1, 1, 0, 1, 0, 0]
mutaion point 0
offspring1: [1, 1, 0, 0, 0, 0, 0]
 offrping 2: [1, 0, 0, 0, 0, 0, 1]
mutaion point 6
offspring1: [0, 0, 0, 0, 0, 0, 0]
 offrping 2: [0, 1, 1, 1, 0, 0, 1]
mutaion point 4
offspring1: [1, 0, 0, 1, 0, 0, 0]
 offrping 

In [1]:
#Odree
# Importing the random and numpy modules
import random
import numpy as np

# Taking input from user for the total number of transactions
total_transactions = int(input("Enter the total number of transactions: "))

# Creating empty lists to store the transaction type and amount for each transaction
transaction_type = []
amount = []

# Looping over number of transactions
for i in range(total_transactions):
    # Take input for transaction type and amount for each transaction
    transaction, amount_new = input(f"Enter transaction {i+1}: ").split()
    transaction_type.append(transaction)
    amount_new = int(amount_new)
    if transaction == "d":
        amount.append(amount_new)
    else:
        amount.append(-amount_new)

# Setting the target sum to zero
target = 0


# Defining a function to generate a population of binary strings
def generate_population(total):
    population = []
    i = 0
    while i < 20:
        x = np.random.randint(2, size=total)
        print(x)
        population.append(x)
        i += 1
    return population


# Defining a function to calculate the fitness of each individual in the population
def calculate_fitness(population):
    scores = []
    i = 0
    while i < len(population):
        total = 0
        for idx, gene in enumerate(population[i]):
            if gene == 1:
                total += amount[idx]
        scores.append(abs(total))
        i += 1
    print(f"Scores: {scores}")
    return scores





# Defining a function to select the most fit individuals from the population
def select_population(scores):
    temp = []
    i = 0
    while i < len(scores):
        temp.append(abs(target - scores[i]))
        i += 1
    least_fit = temp.index(max(temp))
    return least_fit





# Defining a function to crossover between two individual populations
def crossover(x, y):
    crossing = []
    crossover_point = random.randint(1, total_transactions - 2)
    fst_half = []
    lst_half = []
    tmp_fst_half = []
    tmp_lst_half = []

    i = 0
    while i <= crossover_point:
        fst_half.append(x[i])
        tmp_fst_half.append(y[i])
        i += 1

    i = crossover_point + 1
    while i < total_transactions:
        lst_half.append(x[i])
        tmp_lst_half.append(y[i])
        i += 1

    crossing.append(fst_half + tmp_lst_half)
    crossing.append(tmp_fst_half + lst_half)
    return crossing





# mutating ind in the population
def mutate_population(child1, child2):
    mutation_point = random.randint(0, total_transactions - 1)
    if child1[mutation_point] == 1:
        child1[mutation_point] = 0
    else:
        child1[mutation_point] = 1
    if child2[mutation_point] == 1:
        child2[mutation_point] = 0
    else:
        child2[mutation_point] = 1
    return child1, child2




# Initilizng an empty list for result
result = []

for i in range(50):

    # Generating a new population
    population = generate_population(total_transactions)

    # Calculating the fitness of each individual in the population
    scores = calculate_fitness(population)

    # Select the most fit individuals from the population
    least_fit = select_population(scores)

    # Removing the least fit individual from the population
    population.pop(least_fit)

    # Find the solution
    found_solution = False

    for j in range(len(population)):

        # Select two individuals at random to crossbreed
        x = random.choice(population)
        y = random.choice(population)

        # Generating two new children through crossover
        child = crossover(x, y)
        child1, child2 = child[0], child[1]

        # Mutate the children
        child1, child2 = mutate_population(child1, child2)

        # Check if the children have a sum equal to the target
        sum = 0
        for x, el in enumerate(child1):
            if el == 1:
                sum += amount[x]
        if sum == target:
            if child1 != ([0] * total_transactions):
                result = child1
                found_solution = True
                break
        sum = 0
        for x, el in enumerate(child2):
            if el == 1:
                sum += amount[x]
        if sum == target:
            if child2 != ([0] * total_transactions):
                result = child2
                found_solution = True
                break

    # If a solution is found, break out of the loop
    if found_solution == True:
        break

# If no solution is found, print -1
if len(result) == 0:
    print('-1')

# Otherwise, print the solution
else:
    for i in range(len(result)):
        print(result[i], end='')

[0 1 1 0 1 1 1]
[1 0 1 1 1 0 1]
[0 1 1 1 0 0 0]
[1 0 1 1 0 0 1]
[1 0 1 1 1 1 1]
[1 1 0 0 1 0 0]
[0 0 0 1 0 0 1]
[0 1 1 1 0 1 0]
[0 0 1 0 1 0 0]
[0 1 0 1 1 1 1]
[0 1 1 0 0 1 1]
[0 0 0 1 1 0 0]
[1 1 1 0 1 1 1]
[0 0 1 1 0 1 0]
[1 0 1 0 1 1 1]
[0 1 0 1 0 0 1]
[1 0 1 1 0 0 1]
[1 1 0 0 1 1 1]
[1 0 1 1 0 1 0]
[1 1 0 0 1 1 1]
Scores: [7443, 7577, 9, 1095, 7417, 6073, 740, 169, 6957, 6773, 961, 6287, 7323, 120, 7612, 451, 1095, 6848, 0, 6848]
1011010